# Generated by Django 2.2.5 on 2019-10-10 11:01

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_mutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='previous_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
