# Generated by Django 2.2.5 on 2019-10-10 11:01

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations
import funkwhale_api.federation.models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0018_fetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='librarytrack',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=funkwhale_api.federation.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=10000),
        ),
    ]
