# Generated by Django 2.2.5 on 2019-10-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20180320_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'index')},
        ),
    ]
