# Generated by Django 2.2.5 on 2019-10-10 11:01

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import funkwhale_api.music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0039_auto_20190423_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='recording_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='recording_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='recording_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='recording_route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='recording_special_sounds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='recording_start_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='recording_thoughts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='from_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federation.Activity'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='import_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=funkwhale_api.music.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='upload',
            name='import_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=funkwhale_api.music.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='upload',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=funkwhale_api.music.models.empty_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=50000),
        ),
        migrations.AlterField(
            model_name='uploadversion',
            name='mimetype',
            field=models.CharField(choices=[('audio/ogg', 'ogg'), ('audio/opus', 'opus'), ('audio/mpeg', 'mp3'), ('audio/x-flac', 'flac'), ('audio/flac', 'flac')], max_length=50),
        ),
    ]
