# Generated by Django 2.2.5 on 2019-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_auto_20191010_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
