# Generated by Django 2.2.5 on 2019-10-26 16:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0042_auto_20191011_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='recording_device',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='recording_start_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadversion',
            name='mimetype',
            field=models.CharField(choices=[('audio/ogg', 'ogg'), ('audio/opus', 'opus'), ('audio/mpeg', 'mp3'), ('audio/x-flac', 'flac'), ('audio/flac', 'flac'), ('audio/x-wav', 'wav')], max_length=50),
        ),
    ]
