# Generated by Django 2.2.5 on 2019-10-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0043_auto_20191026_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='recording_start_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
