# Generated by Django 2.2.5 on 2019-11-06 11:59

from django.db import migrations, models
import sequences


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0044_auto_20191026_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='inventory_number',
            field=models.CharField(blank=True, default=sequences.get_next_value, editable=False, max_length=20, null=True),
        ),
    ]
