# Generated by Django 2.2.5 on 2019-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0045_upload_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='recording_internal_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
